export default {
  productos: [
    {
      titulo: "Caramelera Tipo Bota De 70cm De Alto 5 Divisiones Acricandy",
      img: "img/producto1.jpg",
      img2: "img/producto6.jpg",
      img3: "img/producto7.jpg",
      precio: "$ 24.900",
      descripcion: "60cm de ANCHO, 30cm de PROFUNDIDAD Y 70cm de ALTO",
      estado: "Nuevo | 20 vendidos",
      cuotas: "en 12 x $2000",
      categoria: "golosinas",
    },
    {
      titulo: "Caramelera C/mueble Golosinakiosco Acricandy",
      img: "img/producto2.jpg",
      precio: "$ 85.000",
      descripcion: "170cm de ANCHO, 95cm PROFUNDIDAD, 20 DIVISIONES.",
      estado: "Nuevo | 5 vendidos",
      cuotas: "en 12 x $2500",
      categoria: "golosinas",
    },
    {
      titulo: "Muebles bonitos y baratos",
      img: "img/producto3.jpg",
      precio: "$ 50.000",
      descripcion: "Mueble de madera, grande a buen precio.",
      estado: "Nuevo",
      cuotas: "en 12 x $2500",
      categoria: "golosinas",
    },
    {
      titulo: "Muebles bonitos y baratos",
      img: "img/producto4.jpg",
      precio: "$ 50.000",
      descripcion: "Mueble de madera, grande a buen precio.",
      estado: "Nuevo",
      cuotas: "en 12 x $2500",
      categoria: "higiene",
    },
    {
      titulo: "Muebles bonitos y baratos",
      img: "img/producto5.jpg",
      precio: "$ 50.000",
      descripcion: "Mueble de madera, grande a buen precio.",
      estado: "Exc Estado",
      cuotas: "en 12 x $2500",
      categoria: "higiene",
    },
    {
      titulo: "Muebles bonitos y baratos",
      img: "img/producto6.jpg",
      precio: "$ 50.000",
      descripcion: "Mueble de madera, grande a buen precio.",
      estado: "Como Nuevo",
      cuotas: "en 12 x $2500",
      categoria: "higiene",
    },
    {
      titulo: "Dispenser Barbijos Cofias Guantes Descartables Acricandy",
      img: "img/producto7.jpg",
      precio: "$ 5.900",
      descripcion:
        "Para los elementos de seguridad e higiene,20cm de ANCHO, 35cm de ALTO y 20cm de PROFUNDIDAD.",
      estado: "Mal Estado",
      cuotas: "en 12 x $2500",
      categoria: "dietetica",
      video: "https://www.youtube.com/embed/frJDr6-L0es",
    },
    {
      titulo: "Muebles bonitos y baratos",
      img: "img/producto8.jpg",
      precio: "$ 50.000",
      descripcion: "Mueble de madera, grande a buen precio.",
      estado: "Semi-Nuevo",
      cuotas: "en 12 x $2500",
      categoria: "dietetica",
    },
  ],
};
