export default {
  productos: [
    {
      titulo: "Caramelera Tipo Bota De 70cm De Alto 5 Divisiones Acricandy",
      id: "carousel1",
      carousel: "#carousel1",
      img: "img/imagen1.jpg",
      img2: "img/imagen2.jpg",
      img3: "img/imagen3.jpg",
      precio: "$ 24.900",
      descripcion: "60cm de ANCHO, 30cm de PROFUNDIDAD Y 70cm de ALTO",
      estado: "Nuevo | 20 vendidos",
      cuotas: "en 12 x $2000",
      categoria: "golosinas",
    },
    {
      titulo: "Caramelera C/mueble Golosinakiosco Acricandy",
      id: "carousel2",
      carousel: "#carousel2",
      img: "img/imagen1.jpg",
      img2: "img/imagen2.jpg",
      img3: "img/imagen3.jpg",
      precio: "$ 85.000",
      descripcion: "170cm de ANCHO, 95cm PROFUNDIDAD, 20 DIVISIONES.",
      estado: "Nuevo | 5 vendidos",
      cuotas: "en 12 x $2500",
      categoria: "golosinas",
    },
    {
      titulo: "Muebles bonitos y baratos",
      id: "carousel3",
      carousel: "#carousel3",
      img: "img/imagen1.jpg",
      img2: "img/imagen2.jpg",
      img3: "img/imagen3.jpg",
      precio: "$ 50.000",
      descripcion: "Mueble de madera, grande a buen precio.",
      estado: "Nuevo",
      cuotas: "en 12 x $2500",
      categoria: "golosinas",
    },
    {
      titulo: "Muebles bonitos y baratos",
      id: "carousel4",
      carousel: "#carousel4",
      img: "img/imagen1.jpg",
      img2: "img/imagen2.jpg",
      img3: "img/imagen3.jpg",
      precio: "$ 50.000",
      descripcion: "Mueble de madera, grande a buen precio.",
      estado: "Nuevo",
      cuotas: "en 12 x $2500",
      categoria: "higiene",
    },
    {
      titulo: "Muebles bonitos y baratos",
      id: "carousel5",
      carousel: "#carousel5",
      img: "img/imagen1.jpg",
      img2: "img/imagen2.jpg",
      img3: "img/imagen3.jpg",
      precio: "$ 50.000",
      descripcion: "Mueble de madera, grande a buen precio.",
      estado: "Exc Estado",
      cuotas: "en 12 x $2500",
      categoria: "higiene",
    },
    {
      titulo: "Muebles bonitos y baratos",
      id: "carousel6",
      carousel: "#carousel6",
      img: "img/imagen1.jpg",
      img2: "img/imagen2.jpg",
      img3: "img/imagen3.jpg",
      precio: "$ 50.000",
      descripcion: "Mueble de madera, grande a buen precio.",
      estado: "Como Nuevo",
      cuotas: "en 12 x $2500",
      categoria: "higiene",
    },
    {
      titulo: "Dispenser Barbijos Cofias Guantes Descartables Acricandy",
      id: "carousel7",
      carousel: "#carousel7",
      img: "img/imagen1.jpg",
      img2: "img/imagen2.jpg",
      img3: "img/imagen3.jpg",
      precio: "$ 5.900",
      descripcion:
        "Para los elementos de seguridad e higiene,20cm de ANCHO, 35cm de ALTO y 20cm de PROFUNDIDAD.",
      estado: "Mal Estado",
      cuotas: "en 12 x $2500",
      categoria: "dietetica",
      video: "https://www.youtube.com/embed/frJDr6-L0es",
    },
    {
      titulo: "Muebles bonitos y baratos",
      id: "carousel8",
      carousel: "#carousel8",
      img: "img/imagen1.jpg",
      img2: "img/imagen2.jpg",
      img3: "img/imagen3.jpg",
      precio: "$ 50.000",
      descripcion: "Mueble de madera, grande a buen precio.",
      estado: "Semi-Nuevo",
      cuotas: "en 12 x $2500",
      categoria: "dietetica",
    },
  ],
};
